feat: рекомендации фильмов на основе лайков
ilya-sayenko/java-filmorate pull request #7
Opened 2023-06-07 17:51 UTC by LisaGavryushkina

2023-06-08 08:50 UTC, ilya-sayenko requested changes

2023-06-08 08:50 UTC, ilya-sayenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +    public List<Film> getRecommendations(int userId) {
Метод возвращает фильмы. Может лучше будет переместить этот метод в FilmDbStorage?

2023-06-08 08:50 UTC, ilya-sayenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +        String sql = "select " +
Попробуй переиспользовать FilmDbStorage.findByIds.

2023-06-08 10:27 UTC, ilya-sayenko requested changes

2023-06-08 10:27 UTC, ilya-sayenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +                " from likes l " +
Можно обойтись без обращения к likes?

2023-06-08 19:25 UTC, LisaGavryushkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +    public List<Film> getRecommendations(int userId) {
этот метод наполовину работает с фильмами и с юзерами и эндпоинт выглядит так: GET /users/{id}/recommendations, поэтому я решила работать  UserController, UserService и тд

2023-06-08 19:29 UTC, LisaGavryushkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +        String sql = "select " +
С учетом того, что я написала выше, я бы могла переиспользовать ```FilmDbStorage.findByIds```, если добавлю в UserDbStorage зависимость с FilmDbStorage. Так будет норм? То есть если хотеть использовать уже существующие методы и для юзеров и для фильмов, придется в одно из хранилищ (где будет метод getRecommendations()) добавлять зависимость с другим хранилищем

2023-06-08 19:50 UTC, ilya-sayenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +        String sql = "select " +
Думаю да, будет норм. Не вижу ничего плохого в использовании одного хранилища в другом.

2023-06-08 22:24 UTC, LisaGavryushkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +        String sql = "select " +
поправила https://github.com/ilya-sayenko/java-filmorate/pull/7/files#diff-f140c93403f49de651f3e6e258aa9136bc27664afe75b9d86795f74d0bbd8568R182
но мне пришлось немного переделать этот метод и метод findAll()

2023-06-09 08:19 UTC, ilya-sayenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/UserDbStorage.java
> +        String sql = "select " +
В целом норм. Можно было и не переделывать, а просто входной лист конвертнуть в массив. Осталось только решить мерж конфликт.

2023-06-09 10:24 UTC, ilya-sayenko approved these changes

2023-06-09 12:22 UTC, strannicamira approved these changes
В целом у меня нет впоросов. 
Комменты очень в тему здесь.
Локально у себя проверила запуск и постман коллекуцию. Всё ок.

2023-06-09 12:22 UTC, strannicamira commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/FilmDbStorage.java
> -    private List<Film> findByIds(int... ids) {
Просто отмечусь.
У меня была тут мысль, что не обязатлеьно было переделывать вызов с (int... ids) на (List<Integer> ids), но я попробовала и в новых условиях, я пришла к вывводу ,что так действильно удобнее и правильнее.

2023-06-09 12:24 UTC, merged